# Autogenerated script from write_samtools_script.R
# date Thu Sep 19 13:36:28 2019
# make sure directory paths exist before running script
#!/bin/bash
#$ -S /bin/bash
#$ -pe smp 1
#$ -cwd
#$ -N samtools-array
#$ -j y
#$ -l h_vmem=2G
#$ -t 1-30



module load bioinformatics/samtools/1.3.1



# Parse parameter file to get variables.
number=$SGE_TASK_ID
paramfile=samtools_param.txt
 
#ins1=`sed -n ${number}p $paramfile | awk '{print $1}'`
bamfile=`sed -n ${number}p $paramfile | awk '{print $1}'`
bamq10=`sed -n ${number}p $paramfile | awk '{print $2}'`
bamq10sort=`sed -n ${number}p $paramfile | awk '{print $3}'`
bamrd=`sed -n ${number}p $paramfile | awk '{print $4}'`

# 9. Run the program.
samtools view -b -q 10 $bamfile > $bamq10
samtools sort -o $bamq10sort $bamq10
samtools index $bamq10sort
samtools rmdup $bamq10sort $bamrd
samtools index $bamrd



